<?php require __DIR__ .'/common/header.phtml'?>
<?php
/** @var $data */
/** @var $errors */
/** @var \jakulov\SignUp\Validator\Validator $validator */
?>
    <div class="container">

        <?php require 'common/lang_switch.phtml'?>

        <form class="form-signin form-horizontal" method="post" id="form">
            <h1 class="form-signin-heading"><?= \jakulov\SignUp\Service\Language::get(RESET_TITLE)?></h1>

            <div class="form-group <?=(isset($errors['password']) ? 'has-error' : '')?>">
                <label class="control-label col-sm-3"><?= \jakulov\SignUp\Service\Language::get(PASSWORD_LABEL)?></label>
                <div class="col-sm-8">
                    <input class="form-control" name="password" type="password" value="<?php \jakulov\SignUp\Service\View::param($data, 'password')?>">
                    <span class="help-block"><?php \jakulov\SignUp\Service\View::param($errors, 'password')?></span>
                </div>
            </div>

            <div class="form-group <?=(isset($errors['password2']) ? 'has-error' : '')?>">
                <label class="control-label col-sm-3"><?= \jakulov\SignUp\Service\Language::get(PASSWORD2_LABEL)?></label>
                <div class="col-sm-8">
                    <input class="form-control" name="password2" type="password" value="<?php \jakulov\SignUp\Service\View::param($data, 'password2')?>">
                    <span class="help-block"><?php \jakulov\SignUp\Service\View::param($errors, 'password2')?></span>
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-sm-3"></label>
                <div class="col-sm-5">
                    <button class="btn btn-lg btn-primary" type="submit">&nbsp;<?=\jakulov\SignUp\Service\Language::get(RESET_TITLE)?>&nbsp;</button>
                </div>
                <div class="col-sm-3">
                    <a href="/sign/in"><?=\jakulov\SignUp\Service\Language::get(CAN_SIGN_IN_LINK)?></a>
                </div>
            </div>
        </form>

        <script>
            $(function() {
                var rules = [];
                <?=($validator->getJsRules())?>
                var Validator = new Validate('#form', rules, <?=\jakulov\SignUp\Service\Language::jsMessages()?>);
            });
        </script>

    </div> <!-- /container -->

<?php require __DIR__ .'/common/footer.phtml'?>