<?php require __DIR__ .'/common/header.phtml'?>
<?php
/** @var $data */
/** @var $errors */
/** @var \jakulov\SignUp\Validator\Validator $validator */
?>
    <div class="container">

        <?php require 'common/lang_switch.phtml'?>

        <form class="form-signin form-horizontal" method="post" id="form">
            <h1 class="form-signin-heading"><?= \jakulov\SignUp\Service\Language::get(SIGN_UP_TITLE)?></h1>

            <div class="form-group <?=(isset($errors['email']) ? 'has-error' : '')?>">
                <label class="control-label col-sm-3"><?= \jakulov\SignUp\Service\Language::get(EMAIL_LABEL)?> *</label>
                <div class="col-sm-8">
                    <input class="form-control" name="email" type="text" value="<?php \jakulov\SignUp\Service\View::param($data, 'email')?>">
                    <span class="help-block"><?php \jakulov\SignUp\Service\View::param($errors, 'email')?></span>
                </div>
            </div>

            <div class="form-group <?=(isset($errors['name']) ? 'has-error' : '')?>">
                <label class="control-label col-sm-3"><?= \jakulov\SignUp\Service\Language::get(NAME_LABEL)?> *</label>
                <div class="col-sm-8">
                    <input class="form-control" name="name" type="text" value="<?php \jakulov\SignUp\Service\View::param($data, 'name')?>">
                    <span class="help-block"><?php \jakulov\SignUp\Service\View::param($errors, 'name')?></span>
                </div>
            </div>

            <div class="form-group <?=(isset($errors['phone']) ? 'has-error' : '')?>">
                <label class="control-label col-sm-3"><?= \jakulov\SignUp\Service\Language::get(PHONE_LABEL)?> *</label>
                <div class="col-sm-8">
                    <input class="form-control" name="phone" type="text" value="<?php \jakulov\SignUp\Service\View::param($data, 'phone')?>">
                    <span class="help-block"><?php \jakulov\SignUp\Service\View::param($errors, 'phone')?></span>
                </div>
            </div>

            <div class="form-group <?=(isset($errors['password']) ? 'has-error' : '')?>">
                <label class="control-label col-sm-3"><?= \jakulov\SignUp\Service\Language::get(PASSWORD_LABEL)?> *</label>
                <div class="col-sm-8">
                    <input class="form-control" name="password" type="password" value="<?php \jakulov\SignUp\Service\View::param($data, 'password')?>">
                    <span class="help-block"><?php \jakulov\SignUp\Service\View::param($errors, 'password')?></span>
                </div>
            </div>

            <div class="form-group <?=(isset($errors['password2']) ? 'has-error' : '')?>">
                <label class="control-label col-sm-3"><?= \jakulov\SignUp\Service\Language::get(PASSWORD2_LABEL)?> *</label>
                <div class="col-sm-8">
                    <input class="form-control" name="password2" type="password" value="<?php \jakulov\SignUp\Service\View::param($data, 'password2')?>">
                    <span class="help-block"><?php \jakulov\SignUp\Service\View::param($errors, 'password2')?></span>
                </div>
            </div>

            <div class="form-group <?=(isset($errors['photo']) ? 'has-error' : '')?>">
                <label class="control-label col-sm-3"><?= \jakulov\SignUp\Service\Language::get(PHOTO_LABEL)?></label>
                <div class="col-sm-8">
                    <input class="form-control" name="photo" type="text" value="<?php \jakulov\SignUp\Service\View::param($data, 'photo')?>">
                    <span class="help-block"><?php \jakulov\SignUp\Service\View::param($errors, 'photo')?></span>
                </div>
            </div>

            <div class="form-group <?=(isset($errors['about']) ? 'has-error' : '')?>">
                <label class="control-label col-sm-3"><?= \jakulov\SignUp\Service\Language::get(ABOUT_LABEL)?></label>
                <div class="col-sm-8">
                    <textarea class="form-control" name="about"><?php \jakulov\SignUp\Service\View::param($data, 'about')?></textarea>
                    <span class="help-block"><?php \jakulov\SignUp\Service\View::param($errors, 'about')?></span>
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-sm-3"></label>
                <div class="col-sm-5">
                    <button class="btn btn-lg btn-success" type="submit">&nbsp;<?=\jakulov\SignUp\Service\Language::get(SIGN_UP_TITLE)?>&nbsp;</button>
                </div>
                <div class="col-sm-3">
                </div>
            </div>
        </form>

        <div class="bottom-form-block">
            <b><?=\jakulov\SignUp\Service\Language::get(CAN_SIGN_IN_TEXT)?> <a class="" href="/sign/in"><?=\jakulov\SignUp\Service\Language::get(CAN_SIGN_IN_LINK)?></a></b>
        </div>

        <script>
            $(function() {
                var rules = [];
                <?=($validator->getJsRules())?>
                var Validator = new Validate('#form', rules, <?=\jakulov\SignUp\Service\Language::jsMessages()?>);
            });
        </script>

    </div> <!-- /container -->

<?php require __DIR__ .'/common/footer.phtml'?>