<?php require __DIR__ .'/common/header.phtml'?>
<?php
/** @var $data */
/** @var $errors */
/** @var \jakulov\SignUp\Validator\Validator $validator */
?>
<div class="container">

    <?php require 'common/lang_switch.phtml'?>

    <form class="form-signin form-horizontal" method="post" id="form">
        <h1 class="form-signin-heading"><?= \jakulov\SignUp\Service\Language::get(SIGN_IN_TITLE)?></h1>

        <div class="form-group <?=(isset($errors['email']) ? 'has-error' : '')?>">
            <label class="control-label col-sm-3"><?= \jakulov\SignUp\Service\Language::get(EMAIL_LABEL)?></label>
            <div class="col-sm-8">
                <input class="form-control" name="email" type="text" value="<?php \jakulov\SignUp\Service\View::param($data, 'email')?>">
                <span class="help-block"><?php \jakulov\SignUp\Service\View::param($errors, 'email')?></span>
            </div>
        </div>

        <div class="form-group <?=(isset($errors['password']) ? 'has-error' : '')?>">
            <label class="control-label col-sm-3"><?= \jakulov\SignUp\Service\Language::get(PASSWORD_LABEL)?></label>
            <div class="col-sm-8">
                <input class="form-control" name="password" type="password" value="<?php \jakulov\SignUp\Service\View::param($data, 'password')?>">
                <span class="help-block"><?php \jakulov\SignUp\Service\View::param($errors, 'password')?></span>
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-sm-3"></label>
            <div class="col-sm-8">
                <label>
                    <input class="checkbox-inline" type="checkbox" <?=(isset($data['remember']) ? 'checked' : '')?> name="remember" value="1">
                    <?= \jakulov\SignUp\Service\Language::get(REMEMBER_ME_LABEL)?>
                </label>
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-sm-3"></label>
            <div class="col-sm-8">
                <label>
                    <input class="checkbox-inline" type="checkbox" <?=(isset($data['bind_ip']) ? 'checked' : '')?> name="bind_ip" value="1">
                    <?= \jakulov\SignUp\Service\Language::get(BIND_IP_LABEL)?>
                </label>
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-sm-3"></label>
            <div class="col-sm-5">
                <button class="btn btn-lg btn-primary" type="submit">&nbsp;<?=\jakulov\SignUp\Service\Language::get(SIGN_IN_TITLE)?>&nbsp;</button>
            </div>
            <div class="col-sm-3">
                <a href="/sign/in/forgot"><?=\jakulov\SignUp\Service\Language::get(FORGOT_LINK)?></a>
            </div>
        </div>
    </form>

    <div class="bottom-form-block" style="background: #feedab;">
        <b><?=\jakulov\SignUp\Service\Language::get(NEED_REGISTER_TEXT)?> <a class="" href="/sign/up"><?=\jakulov\SignUp\Service\Language::get(NEED_REGISTER_LINK)?></a></b>
    </div>

    <script>
        $(function() {
            var rules = [];
            <?=($validator->getJsRules())?>
            var v = new Validate('#form', rules, <?=\jakulov\SignUp\Service\Language::jsMessages()?>);
        });
    </script>

</div> <!-- /container -->

<?php require __DIR__ .'/common/footer.phtml'?>