<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Sample Sign Up Application">
    <meta name="author" content="Yakov Akulov">
    <link rel="icon" href="/favicon.ico">

    <title><?=(isset($title) ? $title .' | ' : '')?><?=\jakulov\SignUp\Service\Language::get(APPLICATION_TITLE);?></title>

    <link href="/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="/css/base.css" rel="stylesheet">

    <script src="/js/jquery-2.2.4.min.js"></script>
</head>

<body>